# Generated by Django 2.1.4 on 2018-12-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountingSubjectNo', models.TextField(max_length=5)),
                ('name', models.TextField(max_length=15)),
                ('scopeofapplication', models.TextField(max_length=15)),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
            },
        ),
        migrations.CreateModel(
            name='AccountingSubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name': '会计科目大类',
                'verbose_name_plural': '会计科目大类',
            },
        ),
        migrations.AddField(
            model_name='accountingsubject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubjectCategory'),
        ),
    ]
