# Generated by Django 2.1.4 on 2018-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingSubjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsubject',
            name='AccountingSubjectNo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accountingsubject',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='accountingsubject',
            name='scopeofapplication',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='accountingsubjectcategory',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
