# Generated by Django 2.1.4 on 2019-01-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingSubjects', '0003_auto_20190102_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSubject_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject2_no', models.CharField(max_length=5, verbose_name='编号')),
                ('name', models.CharField(max_length=15, verbose_name='会计科目二级名称')),
                ('dr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='借方金额')),
                ('cr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='贷方金额')),
                ('scopeofapplication', models.CharField(max_length=15, verbose_name='会计科目适用范围')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject', verbose_name='会计科目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
            },
        ),
    ]
