# Generated by Django 2.1.4 on 2019-01-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingSubjects', '0004_accountingsubject_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingsubject_2',
            options={'verbose_name': '会计科目二级', 'verbose_name_plural': '会计科目二级'},
        ),
        migrations.AlterField(
            model_name='accountingsubject',
            name='AccountingSubjectNo',
            field=models.CharField(max_length=8, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='accountingsubject_2',
            name='subject2_no',
            field=models.CharField(max_length=12, verbose_name='编号'),
        ),
    ]
