# Generated by Django 2.1.4 on 2019-01-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountingSubjects', '0006_auto_20190102_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=10, verbose_name='字 第 号')),
                ('date', models.DateField(verbose_name='凭证日期')),
                ('enclosure', models.IntegerField(default=0)),
                ('total_dr', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_cr', models.DecimalField(decimal_places=2, max_digits=9)),
                ('accounting_supervisor', models.CharField(max_length=6, verbose_name='会计主管')),
                ('book_keepinger', models.CharField(max_length=6, verbose_name='记账')),
                ('cashier', models.CharField(max_length=6, verbose_name='出纳')),
                ('auditor', models.CharField(max_length=6, verbose_name='审核')),
                ('order_makinger', models.CharField(max_length=6, verbose_name='制单')),
            ],
            options={
                'verbose_name': '凭证',
                'verbose_name_plural': '凭证',
            },
        ),
        migrations.CreateModel(
            name='voucher_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brife', models.CharField(max_length=50, verbose_name='摘要')),
                ('dr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='借方金额')),
                ('cr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='贷方金额')),
                ('accountingsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject', verbose_name='会计科目')),
                ('accountingsubject_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject_2', verbose_name='会计科目二级')),
                ('voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher', verbose_name='凭证号码')),
            ],
            options={
                'verbose_name': '凭证具体内容',
                'verbose_name_plural': '凭证具体内容',
            },
        ),
    ]
