# Generated by Django 2.1.4 on 2019-01-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='isbookkeeping',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher_content',
            name='isbookkeeping',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
