# Generated by Django 2.1.4 on 2019-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_auto_20190111_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='enclosure',
            field=models.IntegerField(default=0, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='isbookkeeping',
            field=models.BooleanField(blank=True, null=True, verbose_name='记账√'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_cr',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_dr',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='借方金额'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='cr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='dr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='借方金额'),
        ),
    ]
