# Generated by Django 2.1.4 on 2019-01-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20190117_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='accounting_supervisor',
            field=models.CharField(max_length=12, verbose_name='会计主管'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='auditor',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='审核'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='book_keepinger',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='记账'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='cashier',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='出纳'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='order_makinger',
            field=models.CharField(max_length=12, verbose_name='制单'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_cr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='total_dr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='借方金额'),
        ),
    ]
