# Generated by Django 2.1.4 on 2019-01-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20190118_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_content',
            name='accountingsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject', verbose_name='会计科目'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='accountingsubject_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject_2', verbose_name='会计科目二级'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='brife',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='cr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='贷方金额'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='dr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='借方金额'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher', verbose_name='凭证号码'),
        ),
    ]
