# Generated by Django 2.1.4 on 2019-01-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_auto_20190118_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher_content',
            name='accountingsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.myaccountingsubject', verbose_name='会计科目'),
        ),
        migrations.AlterField(
            model_name='voucher_content',
            name='accountingsubject_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.myaccountingsubject_2', verbose_name='会计科目二级'),
        ),
    ]
