# Generated by Django 2.1.4 on 2019-01-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountingSubjects', '0006_auto_20190102_2148'),
        ('voucher', '0005_auto_20190118_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='凭证日期')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='摘要')),
                ('dr_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='借方金额')),
                ('cr_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='贷方金额')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='余额')),
                ('dr_or_cr', models.CharField(choices=[('dr', '借'), ('cr', '贷')], max_length=2, verbose_name='借或贷')),
                ('isbookkeeping', models.BooleanField(blank=True, null=True)),
                ('accountno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject', verbose_name='总帐科目')),
                ('voucher_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher', verbose_name='凭证字号')),
            ],
            options={
                'verbose_name': '总分类账',
                'verbose_name_plural': '总分类账',
            },
        ),
        migrations.CreateModel(
            name='subsidiary_ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='凭证日期')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='摘要')),
                ('dr_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='借方金额')),
                ('cr_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='贷方金额')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='余额')),
                ('dr_or_cr', models.CharField(choices=[('dr', '借'), ('cr', '贷')], max_length=2, verbose_name='借或贷')),
                ('isbookkeeping', models.BooleanField(blank=True, null=True)),
                ('gen_led_ac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject', verbose_name='总帐科目')),
                ('sub_led_ac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject_2', verbose_name='明细科目')),
                ('voucher_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher', verbose_name='凭证字号')),
            ],
            options={
                'verbose_name': '明细分类账',
                'verbose_name_plural': '明细分类账',
            },
        ),
    ]
