# Generated by Django 2.1.4 on 2019-01-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingSubjects', '0006_auto_20190102_2148'),
        ('ledger', '0002_auto_20190123_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='myaccountingsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountingSubjectNo', models.CharField(max_length=8, verbose_name='编号')),
                ('name', models.CharField(max_length=15, verbose_name='会计科目名称')),
                ('dr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='借方金额')),
                ('cr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='贷方金额')),
                ('scopeofapplication', models.CharField(max_length=30, verbose_name='会计科目适用范围')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubjectCategory', verbose_name='会计科目大类')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
            },
        ),
        migrations.CreateModel(
            name='myaccountingsubject_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject2_no', models.CharField(max_length=12, verbose_name='编号')),
                ('name', models.CharField(max_length=15, verbose_name='会计科目二级名称')),
                ('dr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='借方金额')),
                ('cr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='贷方金额')),
                ('scopeofapplication', models.CharField(max_length=30, verbose_name='会计科目适用范围')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingSubjects.AccountingSubject', verbose_name='会计科目')),
            ],
            options={
                'verbose_name': '会计科目二级',
                'verbose_name_plural': '会计科目二级',
            },
        ),
    ]
