# Generated by Django 2.1.4 on 2019-01-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_myaccountingsubject_myaccountingsubject_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccountingsubject_2',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.myaccountingsubject', verbose_name='会计科目'),
        ),
    ]
