# Generated by Django 2.1.4 on 2019-01-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20190127_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccountingsubject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='myaccountingsubject_2',
            name='subject',
        ),
        migrations.DeleteModel(
            name='myaccountingsubject',
        ),
        migrations.DeleteModel(
            name='myaccountingsubject_2',
        ),
    ]
